version: "3.7"
services:
  db:
    image: mysql/mysql-server:8.0.23
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypaswd
  app:
    build: .
    restart: always
    expose:
      - 5000
    environment:
      FLASK_ENV: dev
  nginx:
    build: ./nginx
    volumes:
      - db-data:/var/log/nginx
    container_name: template_nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - app
volumes:
  db-data:

