version: "3.7"
services:
  db:
    image: mysql/mysql-server:8.0.23
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypaswd

  app:
    build: .
    restart: always
    ports:
      - "5000:5000"
volumes:
  db-data:

